language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yml build --parallel
  - docker tag udagram-frontend nguyenphuochai11t1/udagram-frontend:latest
  - docker tag udagram-api-feed nguyenphuochai11t1/udagram-api-feed:latest
  - docker tag udagram-api-user nguyenphuochai11t1/udagram-api-user:latest
  - docker tag reverseproxy nguyenphuochai11t1/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nguyenphuochai11t1/udagram-frontend
  - docker push nguyenphuochai11t1/udagram-api-feed
  - docker push nguyenphuochai11t1/udagram-api-user
  - docker push nguyenphuochai11t1/reverseproxy
